# Generated by Django 2.2.1 on 2019-05-15 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0002_auto_20190515_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='uptime',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='a.UserGroup'),
        ),
    ]
